baseURL = "https://manuel.kiessling.net"
title = "The Log Book of Manuel Kießling"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Covers topics on architecting, building, deploying and running software and systems for the web based on open source tools with lean methodologies."
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Manuel Kießling"
startYear = "1998"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts", "all_but_recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "manuel@kiessling.net"
github = "manuelkiessling"
twitter = "manuelkiessling"

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Open Source"
weight = 1
identifier = "Open Source"
url = "https://github.com/manuelkiessling"
[[menu.main]]
name = "DX·Tooling"
weight = 2
identifier = "DX Tooling"
url = "https://dx-tooling.org"
[[menu.main]]
name = "Books"
weight = 3
identifier = "Books"
url = "https://leanpub.com/u/manuelkiessling"


[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
